Repository tip-easy/Tip-Easy, pull requests merged in 2019-09, with the labels that each got.

#20 Alex E - Create Type Validation Helper Functions + Request Handling Scaffolding + Add Mock Login Data Processor
  server/package.json
  server/src/app.js
  server/src/data-processors/auth/login-processor.js
  server/src/data-processors/auth/login-processor.test.js
  server/src/data-processors/helpers/generate-token.js
  server/src/data-processors/helpers/generate-token.test.js
  server/src/data-processors/helpers/validate-json-type.js
  server/src/data-processors/helpers/validate-json-type.test.js
  server/src/data-processors/index.js
  server/src/database/mock-response-data.js
  server/src/global-helpers/get-type.js
  server/src/global-helpers/required-parameter.js
  server/src/routes/router.js
Labels: Backend, enhancement

#24 Alex E. - Create Register + Get User Mock Data Processors + Helpers
  server/src/data-processors/auth/register-processor.js
  server/src/data-processors/auth/register-processor.test.js
  server/src/data-processors/helpers/extract-token.js
  server/src/data-processors/helpers/extract-token.test.js
  server/src/data-processors/helpers/verify-auth.js
  server/src/data-processors/index.js
  server/src/data-processors/user/get-user-processor.js
  server/src/data-processors/user/get-user-processor.test.js
  server/src/routes/router.js
Labels: Backend, enhancement

#23 Anthony C. - Full Review of Redux Actions and Reducers
  client/.gitignore
  client/src/Actions/ActionCreators/BalanceActionCreators.js
  client/src/Actions/ActionCreators/DepositActionCreators.js
  client/src/Actions/ActionCreators/LoginActionCreators.js
  client/src/Actions/ActionCreators/PaymentMethodActionCreators.js
  client/src/Actions/ActionCreators/RegistrationActionCreators.js
  client/src/Actions/ActionCreators/TransactionActionCreators.js
  client/src/Actions/ActionCreators/UserActionCreators.js
  client/src/Actions/BalanceActions.js
  client/src/Actions/DepositActions.js
  client/src/Actions/LoginActions.js
  client/src/Actions/PaymentMethodActions.js
  client/src/Actions/RegistrationActions.js
  client/src/Actions/TipReceiverActions.js
  client/src/Actions/TransactionActions.js
  client/src/Actions/UserActions.js
  client/src/Actions/WithdrawActions.js
  client/src/Actions/actionTypes.js
  client/src/Actions/index.js
  client/src/Components/Flows/TippingFlow/EnterCode/EnterCode.js
  client/src/Components/Flows/TippingFlow/SelectAmount/SelectAmount.js
  client/src/Helpers/tokenIsValid.js
  client/src/Reducers/BalanceReducer.js
  client/src/Reducers/DepositReducer.js
  client/src/Reducers/LoginReducer.js
  client/src/Reducers/PaymentMethodReducer.js
  client/src/Reducers/RegistrationReducer.js
  client/src/Reducers/TipReceiverReducer.js
  client/src/Reducers/TipReducer.js
  client/src/Reducers/TransactionReducer.js
  client/src/Reducers/UserReducer.js
  client/src/Reducers/WithdrawalReducer.js
  client/src/Utils/pathVariables.js
  client/src/Utils/tokenIsNotValid.js
  client/src/Utils/tokenIsValid.js
  server/package-lock.json
  server/yarn.lock
Labels: Redux, architecture, front-end

#27 Simplify Backend Architecture + Create Mock Endpoints
  server/package.json
  server/src/app.js
  server/src/data-processors/auth/login-processor.js
  server/src/data-processors/auth/login-processor.test.js
  server/src/data-processors/auth/register-processor.js
  server/src/data-processors/auth/register-processor.test.js
  server/src/data-processors/index.js
  server/src/data-processors/user/get-user-processor.js
  server/src/data-processors/user/get-user-processor.test.js
  server/src/database/index.js
  server/src/database/mock-response-data.js
  server/src/global-helpers/make-interface.js
  server/src/global-helpers/make-interface.test.js
  server/src/http/README.md
  server/src/http/express-http-interface.js
  server/src/http/express-http-interface.test.js
  server/src/http/helpers/normalise-express-request.js
  server/src/http/helpers/normalise-express-request.test.js
  server/src/index.js
  server/src/router/README.md
  server/src/router/index.js
  server/src/router/routes/auth-routes.js
  server/src/router/routes/search-routes.js
  server/src/router/routes/transaction-routes.js
  server/src/router/routes/user-routes.js
  server/src/routes/router-interface.js
  server/src/routes/router-interface.test.js
  server/src/routes/router.js
  server/src/routes/router.test.js
Labels: Backend, Routing, architecture
