Repository tip-easy/Tip-Easy, pull requests merged in 2019-08, with the labels that each got.

#6 Alex E - Establish Server Project File Structure/Architecture
  .gitignore
  server/.gitignore
  server/API_Reference.md
  server/README.md
  server/index.js
  server/package-lock.json
  server/package.json
  server/public/README.md
  server/src/README.md
  server/src/app.js
  server/src/data-processors/README.md
  server/src/database/README.md
  server/src/global-helpers/README.md
  server/src/http/README.md
  server/src/index.js
  server/src/routes/README.md
  server/src/tools/README.md
Labels: architecture, documentation

#5 Workable version of Redux actions and action types.
  client/src/Actions/BalanceActions.js
  client/src/Actions/DepositActions.js
  client/src/Actions/Login.js
  client/src/Actions/LoginActions.js
  client/src/Actions/PaymentMethodActions.js
  client/src/Actions/Registration.js
  client/src/Actions/RegistrationActions.js
  client/src/Actions/TipActions.js
  client/src/Actions/TipReceiverActions.js
  client/src/Actions/TransactionActions.js
  client/src/Actions/UserActions.js
  client/src/Actions/WithdrawActions.js
  client/src/Actions/actionTypes.js
  client/src/App.js
  client/src/App.scss
  client/src/Components/Pages/Auth/Login.js
  client/src/Components/Pages/Auth/Register.js
  client/src/Components/Pages/PaymentFlow/EnterCode/EnterCode.js
  client/src/Components/Pages/PaymentFlow/PaymentDetails.js
  client/src/Components/Pages/PaymentFlow/PaymentDetails/PaymentDetails.js
  client/src/Components/Pages/PaymentFlow/PaymentMethod/PaymentMethod.js
  client/src/Components/Pages/PaymentFlow/PaymentSuccess.js
  client/src/Components/Pages/PaymentFlow/PaymentSuccess/PaymentSuccess.js
  client/src/Components/Pages/PaymentFlow/SelectAmount/SelectAmount.js
  client/src/Components/Pages/UserProfile.js
  client/src/Components/Pages/UserProfile/UserProfile.js
  client/src/Reducers/BalanceReducer.js
  client/src/Reducers/DepositReducer.js
  client/src/Reducers/LoginReducer.js
  client/src/Reducers/PaymentMethodReducer.js
  client/src/Reducers/RegistrationReducer.js
  client/src/Reducers/SelectTip.js
  client/src/Reducers/TipReceiverReducer.js
  client/src/Reducers/TransactionReducer.js
  client/src/Reducers/UserReducer.js
  client/src/Reducers/WithdrawalReducer.js
  client/src/Reducers/index.js
  client/src/index.js
Labels: Redux, enhancement

#8 Reducer and Action implementation
  client/package-lock.json
  client/src/Actions/LoginActions.js
  client/src/Actions/RegistrationActions.js
  client/src/Actions/TipActions.js
  client/src/Actions/TipReceiverActions.js
  client/src/Actions/UserActions.js
  client/src/Actions/index.js
  client/src/App.js
  client/src/Components/Pages/Auth/Auth.js
  client/src/Components/Pages/Auth/Elements/LoginForm.js
  client/src/Components/Pages/Auth/Elements/RegistrationForm.js
  client/src/Components/Pages/Auth/Login.js
  client/src/Components/Pages/PaymentFlow/EnterCode/EnterCode.js
  client/src/Components/Pages/PaymentFlow/SelectAmount/SelectAmount.js
  client/src/Reducers/TipReducer.js
  client/src/Reducers/UserReducer.js
  client/src/Reducers/index.js
  client/src/index.js
Labels: React, Redux, enhancement

#9 Alex E. - Add HTTP Interface Functionality
  server/src/app.js
  server/src/app.test.js
  server/src/global-helpers/make-interface.js
  server/src/global-helpers/make-interface.test.js
  server/src/global-helpers/required-dependency.js
  server/src/http/express-http-interface.js
  server/src/http/express-http-interface.test.js
  server/src/http/helpers/normalise-express-request.js
  server/src/http/helpers/normalise-express-request.test.js
  server/src/routes/express-router-interface.js
  server/src/routes/express-router-interface.test.js
Labels: Backend, Express

#10 Hooking up existing components and pages to Redux Actions and Reducers
  client/src/Actions/PaymentMethodActions.js
  client/src/Actions/actionTypes.js
  client/src/Components/Pages/PaymentFlow/EnterCode/EnterCode.js
  client/src/Components/Pages/PaymentFlow/PaymentMethod/PaymentMethod.js
  client/src/Components/Pages/PaymentFlow/SelectAmount/SelectAmount.js
  client/src/Reducers/PaymentMethodReducer.js
Labels: Redux

#14 Restructured file structure and some basic changes for this week's development
  client/README.md
  client/src/App.js
  client/src/Components/Flows/AuthenticationFlow/Auth.js
  client/src/Components/Flows/AuthenticationFlow/Elements/LoginForm.js
  client/src/Components/Flows/AuthenticationFlow/Elements/RegistrationForm.js
  client/src/Components/Flows/PaymentMethodFlow/PaymentMethodDetails/PaymentMethodDetails.js
  client/src/Components/Flows/PaymentMethodFlow/SelectPaymentMethod/SelectPaymentMethod.js
  client/src/Components/Flows/TippingFlow/EnterCode/EnterCode.js
  client/src/Components/Flows/TippingFlow/SelectAmount/SelectAmount.js
  client/src/Components/HOCs/LoggedIn.js
  client/src/Components/Pages/CommonUse/PaymentSuccess/PaymentSuccess.js
  client/src/Components/Pages/CommonUse/UserSettings/UserSettings.js
  client/src/Components/Pages/Receiver/ReceiverWallet/ReceiverWallet.js
  client/src/Components/Pages/Receiver/ShowReceiverCode/ShowReceiverCode.js
  client/src/Components/Pages/Receiver/WithdrawalAccounts/WithdrawalAccounts.js
  client/src/Components/Pages/Sender/SenderWallet/SenderWallet.js
  client/src/Components/Pages/Sender/UserProfile/UserProfile.js
Labels: architecture

#16 Alex E - Processors Scaffold + Verify Auth Processor Helper
  server/src/app.js
  server/src/data-processors/helpers/verify-auth.js
  server/src/data-processors/helpers/verify-auth.test.js
  server/src/data-processors/index.js
  server/src/database/mock-response-data.js
  server/src/global-helpers/throw-error.js
  server/src/routes/helpers/router.js
  server/src/routes/router-interface.js
Labels: Backend, Express

#18 Alex E - Cleanup Code & Add Comment Annotations
  server/src/app.js
  server/src/database/mock-response-data.js
  server/src/global-helpers/make-interface.js
  server/src/global-helpers/make-interface.test.js
  server/src/global-helpers/required-dependency.js
  server/src/global-helpers/required-parameter.js
  server/src/http/express-http-interface.js
  server/src/http/helpers/normalise-express-request.js
  server/src/routes/router-interface.js
  server/src/routes/router.js
  server/src/routes/router.test.js
Labels: Backend, architecture, documentation

#19 Restructuring Redux Actions and Reducers
  client/src/Actions/BalanceActions.js
  client/src/Actions/DepositActions.js
  client/src/Actions/LoginActions.js
  client/src/Actions/PaymentMethodActions.js
  client/src/Actions/RegistrationActions.js
  client/src/Actions/TipActions.js
  client/src/Actions/TipReceiverActions.js
  client/src/Actions/TransactionActions.js
  client/src/Actions/UserActions.js
  client/src/Actions/WithdrawActions.js
  client/src/Actions/actionTypes.js
  client/src/Actions/index.js
  client/src/Components/Flows/PaymentMethodFlow/SelectPaymentMethod/SelectPaymentMethod.js
  client/src/Components/Flows/TippingFlow/SelectAmount/SelectAmount.js
  client/src/Helpers/tokenIsNotValid.js
  client/src/Helpers/tokenIsValid.js
  client/src/Reducers/BalanceReducer.js
  client/src/Reducers/DepositReducer.js
  client/src/Reducers/LoginReducer.js
  client/src/Reducers/PaymentMethodReducer.js
  client/src/Reducers/RegistrationReducer.js
  client/src/Reducers/TipReceiverReducer.js
  client/src/Reducers/TipReducer.js
  client/src/Reducers/TransactionReducer.js
  client/src/Reducers/UserReducer.js
  client/src/Reducers/WithdrawalReducer.js
  server/package.json
Labels: Redux, front-end

#22 Adding ActionCreators folder and separating out action creators
  client/src/Actions/ActionCreators/BalanceActionCreators.js
  client/src/Actions/ActionCreators/DepositActionCreators.js
  client/src/Actions/ActionCreators/LoginActionCreators.js
  client/src/Actions/ActionCreators/PaymentMethodActionCreators.js
  client/src/Actions/ActionCreators/RegistrationActionCreators.js
  client/src/Actions/ActionCreators/TipActionCreators.js
  client/src/Actions/ActionCreators/TipReceiverActionCreators.js
  client/src/Actions/ActionCreators/TransactionActionCreators.js
  client/src/Actions/ActionCreators/UserActionCreators.js
  client/src/Actions/ActionCreators/WithdrawActionCreators.js
  client/src/Actions/BalanceActions.js
  client/src/Actions/DepositActions.js
  client/src/Actions/LoginActions.js
  client/src/Actions/PaymentMethodActions.js
  client/src/Actions/RegistrationActions.js
  client/src/Actions/TipActions.js
  client/src/Actions/TipReceiverActions.js
  client/src/Actions/TransactionActions.js
  client/src/Actions/UserActions.js
  client/src/Actions/WithdrawActions.js
  client/src/Actions/index.js
  client/src/Components/Flows/TippingFlow/SelectAmount/SelectAmount.js
Labels: Redux, architecture, front-end
